before:
  hooks:
    - go mod tidy
builds:
  - skip: true
release:
  header: |
    ## Changelog ({{ .Date }})
    
    Welcome to this new release! We hope you enjoy the changes we've made.
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'