# .github/workflows/release.yml

name: Release

on:
  push:
    tags:
      - 'v*'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
jobs:
  test:
    permissions:
      checks: write
    uses: ./.github/workflows/main.yml

  release:
    runs-on: ubuntu-latest
    needs: [ test ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod
      - run: make release
        if: success()